### ISSUE TITLE
displayUsing callback is ignored.

### ISSUE THREAD

**Issue by bredmor** [slovenianGooner/nova-searchable-select#13]
Regardless of what is put in the displayUsing callback, the label of the available selections remains the same.

Example:
```
SearchableSelect::make('City Name', 'city_id')
                ->resource(City::class)
                ->displayUsing(function($city) {
                                return "Fake Value"
                })
```

I would expect to see every possible option returned with the label "Fake Value" instead of its normal display attribute.

**Comment by slovenianGooner** [comment]
I think the displayUsing only works on the Detail and Index fields - I tried to apply the same to a normal Select provided by Nova and that was the behaviour I got.
