### ISSUE TITLE
Does Not Respect usesScout() Method

### ISSUE THREAD

**Issue by cotrudel** [slovenianGooner/nova-searchable-select#18]
Our base models use a different search method than our Nova models (primarily to make sure that Nova can search unpublished instances, but the front-end can only search published instances). We enforce this by using Scout for the front-end and having the Nova method `usesScout()` return false on Nova models.

Currently, this package does not respect `usesScout()` -- it tries to search using the underlying model, and bypasses Nova's resource methods. I'm still investigating how to sort this, but it should ideally work similarly to the way that Nova itself calls searches.

**Comment by cotrudel** [comment]
Having investigated, this seems to be semi-intentional behaviour. The controller currently checks whether the base model is searchable or not, and then executes the base model's search if it exists. Given that the example above is fairly common (showing only published instances on the front-end, but showing all instances in the CMS search) I would propose offering the option of using the underlying model search, but defaulting to Nova search.

**Comment by slovenianGooner** [comment]
Hi,  currently I am low on time so if you can make a pull request with the changes I'll review it and tag it for the next release.

**Comment by cotrudel** [comment]
Sorry it took so long to respond -- I might be equally busy. :) I'll try to get a PR in for this, as it's a fairly simple fix.

**Comment by cotrudel** [comment]
#19 Added a PR here.
