### ISSUE TITLE
Adding multiple items + adding mixed resource types

### ISSUE THREAD

**Issue by davidmuggleton** [slovenianGooner/nova-searchable-select#2]
Hi there,

First of, good work with this package - it looks great! I had a couple of questions regarding the existing functionality or whether functionality would be added in the future. 

1) Is it possible to select multiple items in one input?
2) Is it possible to mix the resource types in the results i.e you are able to select a "User" and/or a "Post" in the same input?

Thanks!

**Comment by slovenianGooner** [comment]
Hi David, currently there is no support for both of those out of the box, but I see no reason why it should not work if someone implemented it.

First one would require to use a package that supports multiple selection - this one extends Nova's Select field.

Second one would require a bit of rewrite or an additional method that would not reference a resource directly or maybe add the possibility to add an array of resources in the resource model and then merge the resulting arrays.

Feel free to poke around if you have time, I will have time to do this later this month if possible.

**Comment by davidmuggleton** [comment]
HI @slovenianGooner, thanks for the response. I will certainly take a look too in the coming weeks!

**Comment by slovenianGooner** [comment]
Hi @davidmuggleton,

tried to follow up on your "multiple resources" - but just don't see any sense in it. For it to properly work you would have to write the resource name/class to another field as well which then already translates into relationships so I see no use for it.

As for mutliple selection, I will try to get around to it in the coming days - it will be possible to do `multiple()` when defining a field which will then write an array of IDs into the selected table field.

**Comment by slovenianGooner** [comment]
@davidmuggleton 

Please see https://github.com/slovenianGooner/nova-searchable-select/pull/3 and use release `1.1.0` to enable multiple values in a select.

**Comment by davidmuggleton** [comment]
Hey @slovenianGooner looking good! I will pull this down and take a look when I have a chance..thanks!
