### ISSUE TITLE
Compiled code in development mode

### ISSUE THREAD

**Issue by chrispage1** [slovenianGooner/nova-searchable-select#8]
Hi,

Great plugin - a great asset to our software. However, I noticed that the compiled code is compiled in development mode so we get the Vue devtools prompt...

**Comment by slovenianGooner** [comment]
Thanks for the heads up. Will recompile to production and upload in next version - should be today.

**Comment by chrispage1** [comment]
@slovenianGooner - thank you!

**Comment by slovenianGooner** [comment]
@chrispage1 please see in latest release.
